### ISSUE TITLE
C65 Keyboard diagram incorrect

### ISSUE THREAD

**Issue by sjgray** [MEGA65/c65-specifications#1]
While researching the cursor keys function, looking at the c65 schematics I discovered an error on the 2.1.2 keyboard diagram. The 4066 decoder has 4 switches controlled by 4 lines. The diagram is a bit simplistic, but in essence, there should be a line connecting the 4066 to R4 of the keyboard. C6 and R4 must be connected for the RIGHT shift to be pressed when either K1 or K2 are pressed.

**Comment by gardners** [comment]
Please supply a patched diagram, and we can update it.

**Comment by sjgray** [comment]
+-----+-----+-----+-----+-----+-----+-----+-----+-----+            +-----+
            | C0  | C1  | C2  | C3  | C4  | C5  | C6  | C7  | C8  |            | GND |
            |PIN20|PIN19|PIN18|PIN17|PIN16|PIN15|PIN14|PIN13|PIN-4|            |PIN-1|
            +--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+            +--+--+
               |     |     |     |     |     |     |     |     |                  |
               |     |     |     |     |     |     |     |     |                  |
               V     V     V     V     V     V     V     V     V                  |
+-----+     +-----+-----+-----+-----+-----+-----+-----+-----+-----+               |
| R0  |<----+ INS |  #  |  %  |  '  |  )  |  +  |  £  |  !  | NO  |               |
|PIN12|     | DEL |  3  |  5  |  7  |  9  |     |     |  1  | SCRL|               |
+-----+     +-----+-----+-----+-----+-----+-----+-----+-----+-----+               |
| R1  |<----+ RET |  W  |  R  |  Y  |  I  |  P  |  *  | <-- | TAB |               |
|PIN11|     |     |     |     |     |     |     |     |     |     |               |
+-----+     +-----+-----+-----+-----+-----+-----+-----+-----+-----+               |
| R2  |<----+ HORZ|  A  |  D  |  G  |  J  |  L  |  ]  | CTRL| ALT |               |
|PIN10|     | CRSR|     |     |     |     |     |  ;  |     |     +----------+    |
+-----+     +-----+-----+-----+-----+-----+-----+-----+-----+-----+          |    |
| R3  |<----+ F8  |  $  |  &  |  {  |  0  |  -  | CLR |  "  | HELP|          |    |
|PIN-9|     | F7  |  4  |  6  |  8  |     |     | HOM |  2  |     |          |    |
+-----+     +-----+-----+-----+-----+-----+-----+-----+-----+-----+          |    |
| R4  |<----+ F2  |  Z  |  C  |  B  |  M  |  >  |RIGHT|SPACE| F10 |          |    |
|PIN-8|     | F1  |     |     |     |     |  .  |SHIFT| BAR | F9  +--------+ |    |
+-----+     +-----+-----+-----+-----+-----+-----+-----+-----+-----+        | |    |
| R5  |<----+ F4  |  S  |  F  |  H  |  K  |  [  |  =  | C=  | F12 |        | |    |
|PIN-7|     | F3  |     |     |     |     |  :  |     |     | F11 |        | |    |
+-----+     +-----+-----+-----+-----+-----+-----+-----+-----+-----+        | |    |
| R6  |<----+ F6  |  E  |  T  |  U  |  O  |  @  |  ã  |  Q  | F14 |        | |    |
|PIN-6|     | F5  |     |     |     |     |     |  ^  |     | F13 |        | |    |
+-----+     +-----+-----+-----+-----+-----+-----+-----+-----+-----+        | |    |
| R7  |<----+ VERT|LEFT |  X  |  V  |  N  |  <  |  ?  | RUN | ESC +------+ | |    |
|PIN-5|     | CRSR|SHIFT|     |     |     |  ,  |  /  | STOP|     +--+   | | |    |
+-----+     +-+-+-+--+--+-----+-----+-----+-----+--+--+-----+-----+  |   | | |    |
              | |    |                             |                 |   | | |    |
              | |    |                             +------------+    |   | | |    |
              | +-------------------------------------------+   |    |   | | |    |
              |      |                                      |   |    |   | | |    |
              |   +--+--+     /      (LOCKING)              |   |    |   | | |    |
              |   |SHIFT+----+  +------------------------------------+   | | |    |
              |   | LOCK|                                   |   |        | | |    |
              |   +-----+                                   |   |        | | |    |
              |                            +-------------+  |   |        | | |    |
            +--+--+                        |           C0+--+   |        | | |    |
            |CRSR +------------+-----------+           C6+------+        | | |    |
            | UP  |        K1 PIN-21       |             |               | | |    |
            +--+--+                        |   4066    R7+---------------+ | |    |
              |                            |  DECODER  R4+-----------------+ |    |
            +--+--+                        |             |                   |    |
            |CRSR +------------+-----------+           R2+-------------------+    |
            |LEFT |        K2 PIN-22       |             |                        |
            +-----+                        +-------------+                        |
                                                                                  |
+-----+           +-----+     /                                                   |
| NMI | <---------+RESTR+----+  +-------------------------------------------------+
|PIN-3|           |     |                                                         |
+-----+           +-----+                                                         |
                                                                                  |
                                                                                  |
+-----+           +-----+     /      (LOCKING)                                    |
| R8  | <---------+CAPS +----+  +-------------------------------------------------+
|PIN-2|           |LOCK |
+-----+           +-----+

**Comment by gardners** [comment]
Hmm... github has borked the formatting. Can you please attach it as a .TXT file?
Thanks,
Paul.

**Comment by sjgray** [comment]
[c65keyboard diagram-fixedt.txt](https://github.com/MEGA65/c65-specifications/files/4808242/c65keyboard.diagram-fixedt.txt)

**Comment by SvOlli** [comment]
@gardners : for me this looks good. I already have a version here with this change integrated. If you're okay with it, I'll push it. I also noticed that I've got some smaller changes which are not committed yet. I will add them after this change.

**Comment by gardners** [comment]
@SvOlli that would be fantastic, if you can make a pull-request with that and any other corrections.
